name: "Hello world Workflows" #name of the workflows/pipeline.

#controls when the action will run. Triggers the workflows on push done to master or production branches.
on:
  push:
    branches:
      - master
      - production


jobs:
  hello_world: #name ofthe jobs.
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "hello world"

      - name: "Print current date"
        run: date