name: "Multi Event pipeline / Workflows"

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
    types:
      - closed
      - opened
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 2,4' 
  
jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Runnning on master push"
        run: echo "Runnning on master push"

  on-pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "Runnning on pull request"
        run: echo "Runnning on pull request"
  
  on-pull_request-closed:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request closed"
        run: echo "Running on pull request closed" 
  
  on-pull_request-opened:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request opened"
        run: echo "Running on pull request opened" 
  on-workflow_dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "Runnning on workflow_dispatch"
        run: echo "Runnning on workflow_dispatch"
  on-schedule:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: "Scheduling on particular day & time"
        run: echo "Scheduling on particular day & time"